---
abstract: 'Classes for indent handling.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  Term::ANSIColor: 0
  Test::More: 0
  Test::NoWarnings: 0
  Text::ANSI::Util: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Indent
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  Error::Pure: 0.08
  Exporter: 0
  Readonly: 0
  Text::ANSI::Util: 0.19
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Indent/issues
  homepage: https://github.com/michal-josef-spacek/Indent
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Indent
version: '0.09'
