---
abstract: 'Classes for indent handling.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Indent
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.03
  Error::Pure: 0.08
  Exporter: 0
  Readonly: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Indent
  homepage: https://github.com/tupinek/Indent
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Indent
version: 0.01
