print "Testing: Indenting.\n" if $debug;
my $obj = $class->new;
ok($obj->get, '');
$obj->add('---');
ok($obj->get, '---');
$obj->add('hoho');
ok($obj->get, '---hoho');
$obj->add;
ok($obj->get, "---hoho\t");
$obj->remove;
ok($obj->get, '---hoho');
$obj->remove('hoho');
ok($obj->get, '---');
$obj->remove('---');
ok($obj->get, '');
