print "Testing: Reseting of indent.\n" if $debug;
my $obj = $class->new;
ok($obj->get, '');
$obj->add('---');
ok($obj->get, '---');
$obj->add('hoho');
ok($obj->get, '---hoho');
$obj->reset('|||');
ok($obj->get, "|||");
$obj->add('---');
ok($obj->get, "|||---");
$obj->remove('---');
ok($obj->get, "|||");
$obj->reset;
ok($obj->get, '');
